version: "3.9"

services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - binance_network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - binance_network
    command: ["python", "-m", "app.worker"]

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    networks:
      - binance_network

  alembic:
    build:
      context: ../
    env_file:
      - '../.env'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - binance_network
    command: alembic upgrade head

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - binance_network

networks:
  binance_network:
    driver: bridge
