"""Create currency_rates table

Revision ID: 15e141e8cd8e
Revises:
Create Date: 2024-10-22 23:17:35.031092

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15e141e8cd8e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_currency_rates_id"), "currency_rates", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_currency_rates_symbol"),
        "currency_rates",
        ["symbol"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_currency_rates_symbol"), table_name="currency_rates"
    )
    op.drop_index(op.f("ix_currency_rates_id"), table_name="currency_rates")
    op.drop_table("currency_rates")
    # ### end Alembic commands ###
